### PR TITLE
refactor: renaming drivercom.Message log and drivercom.Log fields

### PR DESCRIPTION
**Pull request by aaumar25**
required for [https://github.com/pmotionf/drivercom-cli/issues/7](https://github.com/pmotionf/drivercom-cli/issues/7)

Changed from plural to singular in drivercom.Log, to match the drivercom.Message.Payload naming scheme.
These changes matters especially for axes and axis, the others are changed for consistency.

### CODE REVIEW

**Review by mochalins — COMMENTED** [review]
What causes the hall_sensor1 vs vehicle_1 difference?

**Comment by mochalins** [comment]
Ok, more specifically, what necessitates vehicle_1?

**Comment by aaumar25** [comment]
Hmm since you mentioning it, I guess the program will still work without even adding "_".
However, the actual reason I add "_" is to make it consistent with the field combinator_and and combinator_or. If we remove "_", it will be hard to read for us.

**Comment by mochalins** [comment]
Hmmm interesting... I don't have strong opinions either way, other than that it's always been a tiny bit more of a hassle to add an underscore just for one number while typing.

Let's try this change and see how it pans out, we can always change it back later.

**Review by mochalins — APPROVED** [review]

**Pull request merged**
